# -*- coding: utf-8 -*-
"""api_deberta

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Pst05CyqpjZWz9wg1yJQC6NmtXtOCP8
"""

from flask import Flask, request
from flask_restx import Api, Resource, fields
from deberta_deployment import predict

app = Flask(__name__)
api = Api(app,
          version="1.0",
          title="DeBERTa Movie Classification API",
          description="API para clasificación de películas - Multigénero",
          doc="/")  # Swagger UI en /

ns = api.namespace("predict", description="Predicción multilabel")

input_model = api.model("InputText", {
    "texts": fields.List(fields.String(required=True, description="Lista de plots a clasificar"), required=True)
})

output_model = api.model("OutputPrediction", {
    "predictions": fields.List(fields.List(fields.Float, description="Probabilidades para cada género")),
    "labels": fields.List(fields.String, description="Géneros de la película")
})

@ns.route("/")
class PredictResource(Resource):
    @ns.expect(input_model, validate=True)
    @ns.marshal_with(output_model)
    def post(self):
        data = request.json
        texts = data["texts"]

        preds, labels = predict(texts)
        return {"predictions": preds, "labels": labels}

if __name__ == "__main__":
    app.run(debug=True, host="0.0.0.0", port=5000)