# -*- coding: utf-8 -*-
"""deberta_deployment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CHGNVxT_otT4vZRSpWXMW7MyTHiCmIJd
"""

import torch
from torch import nn
import joblib
import numpy as np
from transformers import AutoTokenizer, AutoModel

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model_name = "microsoft/deberta-v3-large"

class DebertaClassifier(nn.Module):
    def __init__(self, model_name, num_labels):
        super(DebertaClassifier, self).__init__()
        self.bert = AutoModel.from_pretrained(model_name)
        self.dropout = nn.Dropout(0.4)
        self.classifier = nn.Linear(self.bert.config.hidden_size, num_labels)

    def forward(self, input_ids, attention_mask):
        outputs = self.bert(input_ids=input_ids, attention_mask=attention_mask)
        pooled_output = outputs.last_hidden_state[:, 0]
        pooled_output = self.dropout(pooled_output)
        logits = self.classifier(pooled_output)
        return logits

# Cargar binarizador y modelo
mlb = joblib.load("mlb.pkl")
etiquetas_generos = mlb.classes_.tolist()

model = DebertaClassifier(model_name, num_labels=len(etiquetas_generos))
model.load_state_dict(torch.load("best_model.pt", map_location=device))
model.to(device)
model.eval()

tokenizer = AutoTokenizer.from_pretrained(model_name)

def predict(texts, max_len=512, batch_size=8):
    from torch.utils.data import Dataset, DataLoader

    class PredictionDataset(Dataset):
        def __init__(self, texts, tokenizer, max_len=512):
            self.encodings = tokenizer(texts, truncation=True, padding=True, max_length=max_len)

        def __len__(self):
            return len(self.encodings['input_ids'])

        def __getitem__(self, idx):
            return {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}

    dataset = PredictionDataset(texts, tokenizer, max_len)
    loader = DataLoader(dataset, batch_size=batch_size)

    all_preds = []
    with torch.no_grad():
        for batch in loader:
            input_ids = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)

            outputs = model(input_ids, attention_mask)
            preds = torch.sigmoid(outputs).cpu().numpy()
            all_preds.append(preds)

    Y_prob = np.vstack(all_preds)
    return Y_prob.tolist(), etiquetas_generos